### ISSUE TITLE
Compare strings in isEquals (utils.js)

### ISSUE THREAD

**Issue by Cantoy** [jason80/dragonfly#1]
Compose / decompose strings with `normalize('NFC')` to prevent all cases (ñ length ===1) and (ñ length ===2)

**Comment by jason80** [comment]
Decompose NFC before remove acents (before isEquals() comparing)

**Comment by jason80** [comment]
Decompose NFC before remove acents (before isEquals() comparing)

**Comment by jason80** [comment]
Decompose NFC before remove acents (before isEquals() comparing)
